### ISSUE TITLE
JDK Error windows linux subsystem Ubuntu

### ISSUE THREAD

**Issue by mbernstein-netsuite** [oracle/netsuite-suitecloud-node-cli#12]
Hello, I am a netsuite employee and am trying to create a new account customization project with the following command:
```
scloud createproject --projectname testProject --type ACCOUNTCUSTOMIZATION
```

Returns Error: 
```
Java is not installed on this machine. Install Java JDK version 1.8 to run CLI for Node.js.
```
I have installed JDK 8 and 11 but am still receiving the error.

**Comment by davidecorreu** [comment]
Looks like you don't have java in the path.  You can check it going to a terminal and typing `java -version`
You should see something like:
 `java version "1.8.0_221"`
`Java(TM) SE Runtime Environment (build 1.8.0_221-b11)`
`Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)`

**Comment by mbernstein-netsuite** [comment]
$ java -version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

It is showing it's in the path

**Comment by margabit** [comment]
@mbernstein-netsuite the issue is fixed in the `master` branch. Please try again.
Consider using the interactive mode for better experience:
```
scloud createproject -i
```
Thank you
