### ISSUE TITLE
Switching NS Accounts?

### ISSUE THREAD

**Issue by ShawnTalbert** [oracle/netsuite-suitecloud-node-cli#21]
Hello! With the Java CLI, one can direct it's operation to a specific account by using the `-account ####` option.  

To deploy the same setup to two different sandboxes it would be very useful if we could do `suitecloud deploy--account 123456_SB1`  then follow immediately with  `suitecloud deploy --account 123456_SB2` to hit sandbox1 and sandbox2, respectively.

I didn't see any such options in via `--help`

**Comment by ShawnTalbert** [comment]
I noticed there is an `account.json` file that I presume is what drives this. I also notice that `AccountDetailsService` seems to be prepared to handle multiple accounts?

**Comment by margabit** [comment]
The account management is changing quite a lot in the newest version for 20.1 (dev branch). Account setup will be done through browser-based authentication and it will be much easier to work with multiple accounts. 
The `account.json` file will be removed and instead we're introducing a new project file that will have a default account for the project. However, it will be possible to change the account in each command (same as you propose). 
Thanks for the feedback!

**Comment by ShawnTalbert** [comment]
Thanks Albert! Dare I try out the `dev` branch or should I stay away?

**Comment by margabit** [comment]
Unfortunately, the CLI will probably not work well since the dev version uses a new jar behind the scenes that is not yet available.

**Comment by ShawnTalbert** [comment]
OK, well sounds like this functionality is already slated  for 20.1, so will close this ticket.  It would be nice to be able to run the latest on DEV, understanding it's the work-in-progress branch of development.
